name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
    inputs:
      run_job:
        description: 'Run Specific Job'
        required: false
        type: boolean
      custom_message:
        description: 'Enter a custom message'
        type: string
        required: true

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Printing Custom Message
        run: echo "Exploring Workflow Dispatch Trigger"